/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/rocks.glb -S -T -t 
Files: ./public/models/rocks.glb [3.34KB] > /Users/briankim/Documents/GitHub/stylize-water/rocks-transformed.glb [3.34KB] (0%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    rocks: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

const Rocks = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes } = useGLTF("/models/rocks.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rocks.geometry} material={nodes.rocks.material} />
    </group>
  );
};

export default Rocks;

useGLTF.preload("/models/rocks.glb");
